version: '3.8'
services:
  qrscribe-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qrscribe
    ports:
      - '5433:5432'
    volumes:
      - qrscribe:/var/lib/postgresql/data
volumes:
  qrscribe:
    driver: local
